### ISSUE TITLE
suggestion: modmail auto notify if recipient leave server

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#185] opened 2019-02-21 19:24 UTC
Right now, the only way to find out if the recipient left the server is if moderator respond to the thread and get the error msg in return. I would suggest that the bot automatically send a msg in that same channel that the user left the server so we can close the ticket. 

This is to prevent us waiting days to week for the user to reply back when they arent even there.

**Comment by fourjr** [comment] 2019-02-22 12:16
Duplicate of #121

**Closed by fourjr** 2019-02-22 12:16 UTC
