### ISSUE TITLE
[BUG] Mentions not working after update to latest version

### ISSUE THREAD

**Issue by umamirs** [kyb3r/modmail#2884] opened 2020-11-13 20:58 UTC
**Describe the bug**
Mentions not working after update to latest version

**Bot Info**
3.7.5 (check with `@modmail about`): 

Host method (Heroku, self-host, etc): Heroku

**To Reproduce**
1. Anyone. Send a message to the Modmail to open a ticket.
2. By doing the above. The Modmail does not mention even though a mention is set in the settings.
3. Update caused the issue.
4. Update.
5. Errored

**Error Logs**
Hastebin: https://hasteb.in/igayizid

**Screenshots**
Sorry for the long links but hosted on Discord. 
1) https://cdn.discordapp.com/attachments/529240018934431744/776909186130509834/unknown.png
2) https://cdn.discordapp.com/attachments/529240018934431744/776909234893357076/unknown.png

**Additional context**
There's not really need for additional context. TL;DR the update caused the mention to be bugged. That's it.

**Comment by lorenzo132** [comment] 2020-11-13 21:53
Can verify, doesnt happen to ping anymore on thread creation

**Comment by StephenDaDev** [comment] 2020-11-13 22:07
Duplicate of #2883

**Closed** 2020-11-14 05:36 UTC
Labels: maybe: bug
