### ISSUE TITLE
Suggestion - The possibility to change the message that displays account info

### ISSUE THREAD

**Issue by EGGamer** [kyb3r/modmail#221] opened 2019-05-04 14:50 UTC
![2019-05-04_16-45-53](https://user-images.githubusercontent.com/40073654/57180760-485c5c00-6e8c-11e9-8740-96f6976ed851.png)

When a new thread is open, there's a little line that shows a little bit of information about the author's account, like when did he create the account, when did he join or how many threads opened in the past.

It would be great if we could change that message if we want to translate it, or if we want to add or remove information. This could be done via a config var.

**Comment by fourjr** [comment] 2019-05-13 10:17
What are some usecases? For example, what would you like to edit it to? 

Translations status is being tracked on #103

**Comment by fourjr** [comment] 2019-05-19 14:41
This slightly ties into #171 as we could add variables into these custom messages.

Since there are no urgent/valid use cases raised by the author of the issue, I have labelled it as "low priority".

**Comment by Taaku18** [comment] 2019-07-02 06:01
Duplicate of #300.

**Closed by Taaku18** 2019-07-02 06:01 UTC
Labels: low priority
