### ISSUE TITLE
Support roles for the block command

### ISSUE THREAD

**Issue by Jees1** [kyb3r/modmail#2840] opened 2020-08-09 16:12 UTC
I don’t like when users who are unverified DM the bot, we have a policy that says we can’t help users who aren’t verified cause they haven’t agreed to the rules.

Would be useful if we could block roles with the block command, I would block the unverified role and users with that role won’t be able to DM modmail. 

I’ve thought of channel permissions, though the users have to have permissions to view the server channels.

I believe others will also benefit for this for example, muted users can’t DM modmail, etc.

**Comment by StephenDaDev** [comment] 2020-08-09 17:26
Duplicate of #2753

**Closed** 2020-08-09 17:31 UTC
