### ISSUE TITLE
how to remove  or change mentioned roles by the bot

### ISSUE THREAD

**Issue by scshiv29-dev** [kyb3r/modmail#2839] opened 2020-08-09 15:54 UTC

**Comment by ObjectionSCP** [comment] 2020-08-09 16:09
To change the mention message when a thread is opened, use the "?mention (role/message here)" command to change the mention that the bot does when a thread is opened

**Comment by StephenDaDev** [comment] 2020-08-09 17:25
Duplicate of #2753

**Closed** 2020-08-19 04:13 UTC
