### ISSUE TITLE
 How do I change the language?

### ISSUE THREAD

**Issue by cesarsaiyan1835** [kyb3r/modmail#2854] opened 2020-09-21 23:40 UTC
Could you put some configuration to be able to change the language of the bot?

**Comment by cesarsaiyan1835** [comment] 2020-09-21 23:48
How do I change the language to Spanish?, Could you put some configuration to be able to change the language of the bot?

**Comment by StephenDaDev** [comment] 2020-09-22 02:51
Duplicate of #103 (It is not closed even though it says it is)

**Comment by Starbors** [comment] 2020-09-29 04:43
make a plugin for it

**Comment by cesarsaiyan1835** [comment] 2020-09-29 05:36
how?

**Comment by matrix2113** [comment] 2020-10-15 02:29
Changing the language of Modmail is currently not supported. You would have to translate the text one by one. (which we don't recommend as when the bot updates, you will have to update everything again).

**Comment by fourjr** [comment] 2020-10-28 07:13
Duplicate of #103, you can use the various config options for messages for now.

**Closed by fourjr** 2020-10-28 07:13 UTC
