### ISSUE TITLE
Blocked Notifications

### ISSUE THREAD

**Issue by Gamerholic** [kyb3r/modmail#202] opened 2019-03-19 18:36 UTC
It's not a bug, but it's a suggestion:

Can you make it so we can set a message that is automatically sent to a user when they get blocked?

**Comment by kyb3r** [comment] 2019-03-20 05:54
Not currently

**Comment by Gamerholic** [comment] 2019-03-20 15:07
Please can you add it?

**Comment by fourjr** [comment] 2019-03-20 15:18
Duplicate of #183

**Closed by fourjr** 2019-03-20 15:18 UTC
Labels: duplicate
