### ISSUE TITLE
Global Notify

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#248] opened 2019-05-22 03:07 UTC
To go along with the Global Subscribe Command, I was thinking something more practical, and that would probably be actually used, would be a Global Notify, to notify you for ALL threads when the next message is sent. Works just like normal notify just for every thread instead of just 1

In relation to #246

**Comment by Agent-Fennec** [comment] 2019-05-22 03:10
Duplicate of #246

**Closed** 2019-05-25 05:17 UTC
